### ISSUE TITLE
Error callback VS console.error

### ISSUE THREAD

**Issue by dmassiani** [richardscarrott/require-error-handler-webpack-plugin#3]
Hi,

as you can see here : [stackoverflow](http://stackoverflow.com/questions/33791306/webpack-require-error-callback)
I tried use your plugin and doesn't work. Can you help me?

**Comment by NekR** [comment]
@dmassiani this loader allows you to have `onError` handler: https://github.com/NekR/async-module-loader

**Comment by dmassiani** [comment]
@NekR I use babel-loader. This async loader generate few error on import function :/
I write this code, a simple try/catch and that's work :
$.each( $('body').attr('class').split(' ') , function(index, item) {
    try {
        require("./wordpress/" + item)
    }
    catch (err) {
        return
    }
})

You can close this issue

**Comment by NekR** [comment]
@dmassiani which errors? why not create an issue there to list them?

Btw, your code doesn't load `require("./wordpress/" + item)` in async, it embeds it into bundle.
